### ISSUE TITLE
DirbScan error

### ISSUE THREAD

**Issue by runvirus** [j3ssie/osmedeus#103]
[+] Starting ffuf dirscan
[*] Execute chunk: /tmp/Osmedeus/lib/alias/dirscan -i [[0]] -w '/tmp/Osmedeus/data/wordlists/content/top10000.txt' -o '/root/.osmedeus/workspaces/kfh.com/directory/raw' -p '/tmp/Osmedeus/plugins/go' -s '/root/.osmedeus/workspaces/kfh.com/directory' 
Internal Server Error: /api/cmd/execute/
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.7/dist-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.7/dist-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.7/dist-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/rest_framework/views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python3.7/dist-packages/rest_framework/views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.7/dist-packages/rest_framework/views.py", line 476, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.7/dist-packages/rest_framework/views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "/tmp/Osmedeus/server/api/v1/execute/views.py", line 81, in post
    commands = execute.get_chunk_commands(command_record)
  File "/tmp/Osmedeus/lib/core/execute.py", line 117, in get_chunk_commands
    lists = parse_resources(command.get('resources'))
  File "/tmp/Osmedeus/lib/core/execute.py", line 102, in parse_resources
    final_lists = list(zip(_lists[0].get('content'), itertools.cycle([''])))
TypeError: zip argument #1 must support iteration
[24/Oct/2019 08:03:58] "POST /api/cmd/execute/ HTTP/1.1" 500 16888
[*] Waiting for DirbScan module
[*] Waiting for DirbScan module
[*] Waiting for DirbScan module
[*] Waiting for DirbScan module
[*] Waiting for DirbScan module
[*] Waiting for DirbScan module
[*] Waiting for DirbScan module
[*] Waiting for DirbScan module
[*] Waiting for DirbScan module
[*] Waiting for DirbScan module
[*] Waiting for DirbScan module

how to fix this error ?

**Comment by mayantec** [comment]
I have exactly the same error, and in the container I being using, I can see many <defunct> processes "chromium".

How can I fix this error.
![20191023_osmedeus_015](https://user-images.githubusercontent.com/8841210/67529098-c9005600-f680-11e9-9dc2-0fefd0d45509.png)
![20191023_osmedeus_016](https://user-images.githubusercontent.com/8841210/67529100-c9005600-f680-11e9-8db9-ffa9a72fd972.png)
![20191023_osmedeus_017](https://user-images.githubusercontent.com/8841210/67529102-c9005600-f680-11e9-9055-dd9dfff0299f.png)

**Comment by j3ssie** [comment]
Yeah many process **chromium** happened because **gowitness** sometimes fail and leave that process.

For the error, I will investigate it again and see the root cause.

**Comment by j3ssie** [comment]
The issue is no longer exist due to the repo having been upgraded to [Osmedeus Next Generation v4.0](https://twitter.com/OsmedeusEngine)
