### ISSUE TITLE
AttributeError: 'bool' object has no attribute 'get'

### ISSUE THREAD

**Issue by M0dred** [j3ssie/osmedeus#113]
uname -a
5.2.0-kali3-amd64 #1 SMP Debian 5.2.17-1kali2 (2019-10-17) x86_64 GNU/Linux

python3 -V
Python 3.7.5

[*] Loading config file from: /root/.osmedeus/client.conf
Traceback (most recent call last):
  File "./osmedeus.py", line 159, in <module>
    main()
  File "./osmedeus.py", line 155, in main
    parsing_argument(args)
  File "./osmedeus.py", line 35, in parsing_argument
    options = config.parsing_config(args)
  File "/opt/github/Osmedeus/lib/client/config.py", line 107, in parsing_config
    config_path, remote, credentials)
  File "/opt/github/Osmedeus/lib/client/config.py", line 54, in _config_file_handle
    remote, credentials = _handle_remote(remote, credentials, configs)
  File "/opt/github/Osmedeus/lib/client/config.py", line 69, in _handle_remote
    config_remote = configs.get('Server', 'remote_api')
AttributeError: 'bool' object has no attribute 'get'

**Comment by M0dred** [comment]
I just run ./osmedeus.py -t  target

**Comment by j3ssie** [comment]
This happened because this #111 or after you reinstall Osmedeus?

**Comment by j3ssie** [comment]
The issue is no longer exist due to the repo having been upgraded to [Osmedeus Next Generation v4.0](https://twitter.com/OsmedeusEngine)
