### ISSUE TITLE
Database Locked

### ISSUE THREAD

**Issue by dzhenway** [j3ssie/Osmedeus#122]
Hi,

I got some error when trying running `Osmedeus`

Result :

```
Internal Server Error: /api/reports/real/
Traceback (most recent call last):
  File "/home/wayc0de/.local/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/wayc0de/.local/lib/python3.7/site-packages/django/db/backends/sqlite3/base.py", line 383, in execute          return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: database is locked
```

How to fix that?

Thank

**Comment by j3ssie** [comment]
Can you just delete `Osmedeus/server/db.sqlite3` and run the following commands below to create new db.

```
python3 server/manage.py makemigrations
python3 server/manage.py migrate
python3 server/manage.py makemigrations api
python3 server/manage.py migrate api
python3 scripts/init.py
python3 scripts/reload.py
```

**Comment by dzhenway** [comment]
worked!!

Thank sir
