### ISSUE TITLE
Running with repot mode error

### ISSUE THREAD

**Issue by fr33wi11** [j3ssie/osmedeus#129]
When I try to run it like

> ./osmedeus.py -t example.com --report full   > 

It gives me following error.

`----------------------------------------------------------------------                                                                                                                                       
          ^O^ Running with report mode ^O^                                                                                                                                                                   
----------------------------------------------------------------------                                                                                                                                       
[-] Workpsace not found                                                                                                                                                                                      
Traceback (most recent call last):                                                                                                                                                                           
  File "./osmedeus.py", line 161, in <module>                                                                                                                                                                
    main()                                                                                                                                                                                                   
  File "./osmedeus.py", line 157, in main                                                                                                                                                                    
    parsing_argument(args)                                                                                                                                                                                   
  File "./osmedeus.py", line 58, in parsing_argument                                                                                                                                                         
    single_target(options)                                                                                                                                                                                   
  File "./osmedeus.py", line 66, in single_target                                                                                                                                                            
    routine.routine_handle(options)                                                                                                                                                                          
  File "/home/kali/Desktop/q/Osmedeus/lib/mode/routine.py", line 16, in routine_handle                                                                                                                
    report.handle(options)                                                                                                                                                                                   
  File "/home/kali/Desktop/kashif-q/Osmedeus/lib/mode/report.py", line 39, in handle                                                                                                                         
    options = parse_options(options)                                                                                                                                                                         
  File "/home/kali/Desktop/q/Osmedeus/lib/mode/report.py", line 22, in parse_options                                                                                                                  
    options = {**options, **arguments}                                                                                                                                                                       
TypeError: 'bool' object is not a mapping                                                                                                                                                                    
^X^CError in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/lib/python3.7/multiprocessing/popen_fork.py", line 28, in poll
    pid, sts = os.waitpid(self.pid, flag)
KeyboardInterrupt
`

**Comment by j3ssie** [comment]
the workspace folder exists in `~/.osmedeus/workspaces/<your_target>` ?

**Comment by 1UC1F3R616** [comment]
@j3ssie for me also, .osmedeus folder is missing and this leads to many other issues like missing confi file etc, I am not sure why.
I am using Kali Linux and installed as given in the docs (*sudo su* was also done)

**Comment by j3ssie** [comment]
The issue is no longer exist due to the repo having been upgraded to [Osmedeus Next Generation v4.0](https://twitter.com/OsmedeusEngine)
