### ISSUE TITLE
Issue on Django API

### ISSUE THREAD

**Issue by nittoworld** [j3ssie/Osmedeus#140]
Hello,
I was installing this and facing a lot of errors, few of them i have resolved but this is still difficult for me right now. Please Help.

[*] Loading config file from: /home/nittonull/.osmedeus/client.conf
----------------------------------------------------------------------
[RUN] Starting Django API
----------------------------------------------------------------------
Performing system checks...

AttributeError: cffi library '_constant_time' has no function, constant or global variable named '__spec__'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "server/manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/home/nittonull/.local/lib/python3.7/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/home/nittonull/.local/lib/python3.7/site-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/nittonull/.local/lib/python3.7/site-packages/django/core/management/base.py", line 328, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/nittonull/.local/lib/python3.7/site-packages/django/core/management/commands/runserver.py", line 60, in execute
    super().execute(*args, **options)
  File "/home/nittonull/.local/lib/python3.7/site-packages/django/core/management/base.py", line 369, in execute
    output = self.handle(*args, **options)
  File "/home/nittonull/.local/lib/python3.7/site-packages/django/core/management/commands/runserver.py", line 95, in handle
    self.run(**options)
  File "/home/nittonull/.local/lib/python3.7/site-packages/django/core/management/commands/runserver.py", line 102, in run
    autoreload.run_with_reloader(self.inner_run, **options)
  File "/home/nittonull/.local/lib/python3.7/site-packages/django/utils/autoreload.py", line 599, in run_with_reloader
    start_django(reloader, main_func, *args, **kwargs)
  File "/home/nittonull/.local/lib/python3.7/site-packages/django/utils/autoreload.py", line 584, in start_django
    reloader.run(django_main_thread)
  File "/home/nittonull/.local/lib/python3.7/site-packages/django/utils/autoreload.py", line 299, in run
    self.run_loop()
  File "/home/nittonull/.local/lib/python3.7/site-packages/django/utils/autoreload.py", line 305, in run_loop
    next(ticker)
  File "/home/nittonull/.local/lib/python3.7/site-packages/django/utils/autoreload.py", line 345, in tick
    for filepath, mtime in self.snapshot_files():
  File "/home/nittonull/.local/lib/python3.7/site-packages/django/utils/autoreload.py", line 361, in snapshot_files
    for file in self.watched_files():
  File "/home/nittonull/.local/lib/python3.7/site-packages/django/utils/autoreload.py", line 260, in watched_files
    yield from iter_all_python_module_files()
  File "/home/nittonull/.local/lib/python3.7/site-packages/django/utils/autoreload.py", line 105, in iter_all_python_module_files
    return iter_modules_and_files(modules, frozenset(_error_files))
  File "/home/nittonull/.local/lib/python3.7/site-packages/django/utils/autoreload.py", line 126, in iter_modules_and_files
    if getattr(module, '__spec__', None) is None:
SystemError: <built-in function getattr> returned a result with an error set
Traceback (most recent call last):
  File "osmedeus.py", line 161, in <module>
    main()
  File "osmedeus.py", line 157, in main
    parsing_argument(args)
  File "osmedeus.py", line 46, in parsing_argument
    options = auth.login(options)
  File "/home/nittonull/Downloads/Osmedeus/lib/sender/auth.py", line 16, in login
    if r.json().get('access'):
AttributeError: 'NoneType' object has no attribute 'json'

**Comment by nittoworld** [comment]
It worked later.

**Comment by shariarr** [comment]
> It worked later.

How did u resolve this?
