### ISSUE TITLE
Lot of errors to solve.

### ISSUE THREAD

**Issue by nittoworld** [j3ssie/osmedeus#142]
python3 osmedeus.py -t Target.com
Traceback (most recent call last):
  File "osmedeus.py", line 13, in <module>
    from lib.mode import routine
  File "/home/nittonull/Downloads/Osmedeus/lib/mode/routine.py", line 6, in <module>
    from lib.mode import general
  File "/home/nittonull/Downloads/Osmedeus/lib/mode/general.py", line 6, in <module>
    from modules import subdomain
  File "/home/nittonull/Downloads/Osmedeus/modules/subdomain.py", line 1, in <module>
    from modules import skeleton
  File "/home/nittonull/Downloads/Osmedeus/modules/skeleton.py", line 7, in <module>
    from lib.monitor import compare
  File "/home/nittonull/Downloads/Osmedeus/lib/monitor/compare.py", line 10, in <module>
    from lib.noti import slack_noti
  File "/home/nittonull/Downloads/Osmedeus/lib/noti/slack_noti.py", line 6, in <module>
    import slack
  File "/usr/local/lib/python3.7/dist-packages/slack/__init__.py", line 4, in <module>
    from slack.web.client import WebClient  # noqa
  File "/usr/local/lib/python3.7/dist-packages/slack/web/client.py", line 9, in <module>
    from slack.web.base_client import BaseClient, SlackResponse
  File "/usr/local/lib/python3.7/dist-packages/slack/web/base_client.py", line 15, in <module>
    import aiohttp
  File "/usr/lib/python3/dist-packages/aiohttp/__init__.py", line 6, in <module>
    from .client import BaseConnector as BaseConnector
  File "/usr/lib/python3/dist-packages/aiohttp/client.py", line 63, in <module>
    from .client_reqrep import ClientRequest as ClientRequest
  File "/usr/lib/python3/dist-packages/aiohttp/client_reqrep.py", line 29, in <module>
    from . import hdrs, helpers, http, multipart, payload
  File "/usr/lib/python3/dist-packages/aiohttp/multipart.py", line 703, in <module>
    class MultipartWriter(Payload):
  File "/usr/lib/python3/dist-packages/aiohttp/multipart.py", line 786, in MultipartWriter
    headers: Optional[MultiMapping[str]]=None
TypeError: 'ABCMeta' object is not subscriptable

**Comment by j3ssie** [comment]
The issue is no longer exist due to the repo having been upgraded to [Osmedeus Next Generation v4.0](https://twitter.com/OsmedeusEngine)
