### ISSUE TITLE
error occured while running osmedeus.py 

### ISSUE THREAD

**Issue by abuvanth** [j3ssie/Osmedeus#147]
Traceback (most recent call last):
  File "./osmedeus.py", line 161, in <module>
    main()
  File "./osmedeus.py", line 70, in main
    config.banner(__version__, __author__)
  File "/home/.recon/Osmedeus/lib/client/config.py", line 17, in banner
    banner_(__version__, __author__)
  File "/home/.recon/Osmedeus/lib/client/banner.py", line 45, in banner_
    """.format(C, G, P, R, B, GR, __version__, __author__))
UnicodeEncodeError: 'ascii' codec can't encode character '\xaf' in position 1303: ordinal not in range(128)

OS: centos

**Comment by j3ssie** [comment]
Your python version should be 3.6+
