### ISSUE TITLE
[-] Fail to set config, Please check Flask API !!!

### ISSUE THREAD

**Issue by veter069** [j3ssie/Osmedeus#15]
I have an error when try to run this tool for the 1st time on Kali Linux.

```
root@lon-host1:~/pentest/web/Osmedeus# ./osmedeus.py -t duckduckgo.com
...
[*] Config file detected: core/config.conf
--~~~=:>[ Starting Flask API ]>
[+] Make new directory: /root/pentest/web/Osmedeus/workspaces/duckduckgo.com
 * Serving Flask app "app" (lazy loading)
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: on
Traceback (most recent call last):
  File "core/app.py", line 93, in <module>
    app.run(debug=True)  # important to mention debug=True
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 943, in run
    run_simple(host, port, self, **options)
  File "/usr/local/lib/python3.7/dist-packages/werkzeug/serving.py", line 988, in run_simple
    run_with_reloader(inner, extra_files, reloader_interval, reloader_type)
  File "/usr/local/lib/python3.7/dist-packages/werkzeug/_reloader.py", line 322, in run_with_reloader
    reloader = reloader_loops[reloader_type](extra_files, interval)
  File "/usr/local/lib/python3.7/dist-packages/werkzeug/_reloader.py", line 213, in __init__
    from watchdog.observers import Observer
ImportError: cannot import name 'Observer' from 'watchdog.observers' (unknown location)
[-] Fail to set config, Please check Flask API !!!
```

Here is my Osmedeus/core/config.conf
```
[Enviroments]
cwd = /root/pentest/web/Osmedeus
workspaces = /root/pentest/web/Osmedeus/workspaces/
workspace = /root/pentest/web/Osmedeus/workspaces/duckduckgo.com
plugins_path = ${CWD}/plugins
go_path = /root/go/bin
github_api_key = None

[Resources]
directory_full = ${Enviroments:plugins_path}/wordlists/dir-all.txt
domain_full = ${Enviroments:plugins_path}/wordlists/all.txt
domain_short = ${Enviroments:plugins_path}/wordlists/shorts.txt

[Slack]
local_name = JJ
bot_token = None
log_channel = None
log_name = logcmd
status_channel = None
status_name = status
stds_channel = None
stds_name = stds
report_channel = None
report_name = report
verbose_report_channel = None
verbose_report_name = verbose-report

[Mode]
speed = quick
module = None
debug = False

[Target]
target = duckduckgo.com
target_list = None
company = duckduckgo.com
strip_target = duckduckgo.com
git_target = None
burpstate_target = None
ip = 46.51.179.90
output = duckduckgo.com
more = 
```

How to fix this issue?

**Comment by j3ssie** [comment]
Could you start flask manually by using this command `python3 core/app.py run`
And run `./osmedeus.py -t example.com —client`
P/s: make sure you ran `install.sh` file

**Comment by veter069** [comment]
Still have error.
```
root@lon-host1:~/pentest/web/Osmedeus# python3 core/app.py
 * Serving Flask app "app" (lazy loading)
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: on
Traceback (most recent call last):
  File "core/app.py", line 93, in <module>
    app.run(debug=True)  # important to mention debug=True
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 943, in run
    run_simple(host, port, self, **options)
  File "/usr/local/lib/python3.7/dist-packages/werkzeug/serving.py", line 988, in run_simple
    run_with_reloader(inner, extra_files, reloader_interval, reloader_type)
  File "/usr/local/lib/python3.7/dist-packages/werkzeug/_reloader.py", line 322, in run_with_reloader
    reloader = reloader_loops[reloader_type](extra_files, interval)
  File "/usr/local/lib/python3.7/dist-packages/werkzeug/_reloader.py", line 213, in __init__
    from watchdog.observers import Observer
ImportError: cannot import name 'Observer' from 'watchdog.observers' (unknown location)
```
```
root@lon-host1:~/pentest/web/Osmedeus# ./osmedeus.py -t duckduckgo.com -client
...
[*] New config file created: lient
--~~~=:>[ Starting Flask API ]>
 * Serving Flask app "app" (lazy loading)
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: on
Traceback (most recent call last):
  File "core/app.py", line 93, in <module>
    app.run(debug=True)  # important to mention debug=True
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 943, in run
    run_simple(host, port, self, **options)
  File "/usr/local/lib/python3.7/dist-packages/werkzeug/serving.py", line 988, in run_simple
    run_with_reloader(inner, extra_files, reloader_interval, reloader_type)
  File "/usr/local/lib/python3.7/dist-packages/werkzeug/_reloader.py", line 322, in run_with_reloader
    reloader = reloader_loops[reloader_type](extra_files, interval)
  File "/usr/local/lib/python3.7/dist-packages/werkzeug/_reloader.py", line 213, in __init__
    from watchdog.observers import Observer
ImportError: cannot import name 'Observer' from 'watchdog.observers' (unknown location)
[-] Fail to set config, Please check Flask API !!!
```
```
root@lon-host1:~/pentest/web/Osmedeus# ./osmedeus.py -t duckduckgo.com --client
...
[*] Config file detected: core/config.conf
[-] Fail to set config, Please check Flask API !!!
```

**Comment by j3ssie** [comment]
Look like you can't start Flask API by using this command `python3 core/app.py run`.
Did you run the `install.sh` file or at least install some lib on the `app.py` file?

If you did try to comment 
```
log = logging.getLogger('werkzeug')
log.setLevel(logging.ERROR)
```
in the `app.py` file and start it again and access http://127.0.0.1:5000

**Comment by veter069** [comment]
- Did you run the install.sh file or at least install some lib on the app.py file?
- Yes i'm run install.sh.

app.py Ln 31-37 now
```
############
## Flask config 
##
## turn off the http log
#log = logging.getLogger('werkzeug')
#log.setLevel(logging.ERROR)
###
```

```
root@lon-host1:~/pentest/web/Osmedeus# ./osmedeus.py -t duckduckgo.com --client
[*] Config file detected: core/config.conf
[-] Fail to set config, Please check Flask API !!!
```

```
root@lon-host1:~/pentest/web/Osmedeus# ./osmedeus.py -t duckduckgo.com
...
[*] Config file detected: core/config.conf
--~~~=:>[ Starting Flask API ]>
 * Serving Flask app "app" (lazy loading)
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: on
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
Traceback (most recent call last):
  File "core/app.py", line 93, in <module>
    app.run(debug=True)  # important to mention debug=True
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 943, in run
    run_simple(host, port, self, **options)
  File "/usr/local/lib/python3.7/dist-packages/werkzeug/serving.py", line 988, in run_simple
    run_with_reloader(inner, extra_files, reloader_interval, reloader_type)
  File "/usr/local/lib/python3.7/dist-packages/werkzeug/_reloader.py", line 322, in run_with_reloader
    reloader = reloader_loops[reloader_type](extra_files, interval)
  File "/usr/local/lib/python3.7/dist-packages/werkzeug/_reloader.py", line 213, in __init__
    from watchdog.observers import Observer
ImportError: cannot import name 'Observer' from 'watchdog.observers' (unknown location)
[-] Fail to set config, Please check Flask API !!!
```
Unable to connect in FF browser.

```
root@lon-host1:~# nmap -sN -sV 127.0.0.1 -p 5000
Starting Nmap 7.70 ( https://nmap.org ) at 2019-04-18 04:59 +05
Nmap scan report for localhost (127.0.0.1)
Host is up (0.000076s latency).

PORT     STATE  SERVICE VERSION
5000/tcp closed upnp

Service detection performed. Please report any incorrect results at https://nmap.org/submit/ .
Nmap done: 1 IP address (1 host up) scanned in 0.61 seconds
root@lon-host1:~# nc 127.0.0.1 5000
(UNKNOWN) [127.0.0.1] 5000 (?) : Connection refused
```

**Comment by veter069** [comment]
I make fresh install Kali in VMware & install this tool have the same error "[-] Fail to set config, Please check Flask API !!!"

**Comment by j3ssie** [comment]
First of all, I'm working new release to resolve a bunch of bug like that. Sorry for this inconvenience.
Your error is because Flask API cannot run. So until you can run` python3 core/app.py run` manually and successfully connects to it. Nothing of this tool gonna works.
Could you please DM me via @j3ssiejjj on twitter to give me more detail.

**Comment by dagda76** [comment]
I was getting the same error. install.sh failed to install several items, including selenium-requests. I had to install pandoc before I could install selenium-requests (sudo apt-get install pandoc).
