### ISSUE TITLE
error while executing

### ISSUE THREAD

**Issue by ngxxx** [j3ssie/Osmedeus#150]
Traceback (most recent call last):
  File "./osmedeus.py", line 9, in <module>
    from lib.core import utils
  File "/root/Osmedeus/lib/core/utils.py", line 24, in <module>
    import tldextract
ModuleNotFoundError: No module named 'tldextract'

downloaded the new version of tldextract module but still got errors could'nt execute it fully

**Comment by j3ssie** [comment]
Please run `pip3 install -r requirements.txt` first.
