### ISSUE TITLE
django.db.utils.OperationalError: database is locked

### ISSUE THREAD

**Issue by im403** [j3ssie/osmedeus#168]
https://stackoverflow.com/questions/3172929/operationalerror-database-is-locked 

can u check this issue please

![image](https://user-images.githubusercontent.com/26847226/86628094-ff9bb800-bfe6-11ea-9750-c43fa5c8ec92.png)

**Comment by kernelzeroday** [comment]
This occurs for me when using the docker image and a previously open session interacts with a fresh instance using a bad token. Database locks right up. 

^[[AInternal Server Error: /api/workspaces/                                                                
Traceback (most recent call last):                                                                                                                                                                         
  File "/usr/local/lib/python3.7/dist-packages/django/db/backends/utils.py", line 84, in _execute        
    return self.cursor.execute(sql, params)                                                             
  File "/usr/local/lib/python3.7/dist-packages/django/db/backends/sqlite3/base.py", line 383, in execute            
    return Database.Cursor.execute(self, query, params)                                        
sqlite3.OperationalError: database is locked

**Comment by j3ssie** [comment]
The issue is no longer exist due to the repo having been upgraded to [Osmedeus Next Generation v4.0](https://twitter.com/OsmedeusEngine)
