### ISSUE TITLE
Error while running osmedeus.py 

### ISSUE THREAD

**Issue by rahul-nakum** [j3ssie/Osmedeus#179]
Traceback (most recent call last):
  File "osmedeus.py", line 161, in <module>
    main()
  File "osmedeus.py", line 70, in main
    config.banner(__version__, __author__)
  File "C:\Users\Rahul Nakum\Osmedeus\lib\client\config.py", line 17, in banner
    banner_(__version__, __author__)
  File "C:\Users\Rahul Nakum\Osmedeus\lib\client\banner.py", line 20, in banner_
    print(r"""{1}
  File "C:\Users\Rahul Nakum\AppData\Local\Programs\Python\Python38-32\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u30c4' in position 1331: character maps to <undefined>

Python version is: 3.8.2  
Os: Windows

**Comment by 1UC1F3R616** [comment]
@rahul-nakum use it with docker on windows, It works like charm
