### ISSUE TITLE
ImportError: cannot import name 'utils' from 'core' 

### ISSUE THREAD

**Issue by VigneshSahoo** [j3ssie/osmedeus#188]
Installation took 1 hour and now this error.  Damn!! 

Traceback (most recent call last):
  File "./osmedeus.py", line 10, in <module>
    from lib.client import config
  File "/home/robin/Desktop/sourcediv/Osmedeus/lib/client/config.py", line 7, in <module>
    from lib.core import execute
  File "/home/robin/Desktop/sourcediv/Osmedeus/lib/core/execute.py", line 8, in <module>
    from core import utils
ImportError: cannot import name 'utils' from 'core' (/usr/local/lib/python3.8/dist-packages/OWASP_Nettacker-0.0.1-py3.8.egg/core/__init__.py)

**Comment by j3ssie** [comment]
The issue is no longer exist due to the repo having been upgraded to [Osmedeus Next Generation v4.0](https://twitter.com/OsmedeusEngine)
