### ISSUE TITLE
 Pls help me this error: From core import utils

### ISSUE THREAD

**Issue by phanthuthao** [j3ssie/osmedeus#193]
sudo ./osmedeus.py -t barnesandnoble.com
Traceback (most recent call last):
  File "./osmedeus.py", line 10, in <module>
    from lib.client import config
  File "/home/joker2020/soft/Osmedeus/lib/client/config.py", line 7, in <module>
    from lib.core import execute
  File "/home/joker2020/soft/Osmedeus/lib/core/execute.py", line 8, in <module>
    From core import utils
ImportError: cannot import name 'utils' from 'core' (/usr/local/lib/python3.8/dist-packages/ufonet-1.5-py3.8.egg/core/__init__.py)

**Comment by j3ssie** [comment]
The issue is no longer exist due to the repo having been upgraded to [Osmedeus Next Generation v4.0](https://twitter.com/OsmedeusEngine)
