### ISSUE TITLE
Error running Osmedeus

### ISSUE THREAD

**Issue by Dayaaol** [j3ssie/osmedeus#194]
When i try to run Osmedeus i got this error 

sudo ./osmedeus.py -t viator.com                                   1 ⨯
Traceback (most recent call last):
  File "/home/daya/Osmedeus/./osmedeus.py", line 13, in <module>
    from lib.mode import routine
  File "/home/daya/Osmedeus/lib/mode/routine.py", line 6, in <module>
    from lib.mode import general
  File "/home/daya/Osmedeus/lib/mode/general.py", line 6, in <module>
    from modules import subdomain
  File "/home/daya/Osmedeus/modules/subdomain.py", line 1, in <module>
    from modules import skeleton
  File "/home/daya/Osmedeus/modules/skeleton.py", line 7, in <module>
    from lib.monitor import compare
  File "/home/daya/Osmedeus/lib/monitor/compare.py", line 10, in <module>
    from lib.noti import slack_noti
  File "/home/daya/Osmedeus/lib/noti/slack_noti.py", line 6, in <module>
    import slack
ModuleNotFoundError: No module named 'slack'

How to resolve this???

Kali Version 2020.4

**Comment by Liquid1998** [comment]
simply do "pip3 install slack"

It will solve ur issue

**Comment by aaryan778** [comment]
> 
> 
> simply do "pip3 install slack"
> 
> It will solve ur issue

Yeah bro,tried that too. I was facing the same problem and installed slack too but to no avail.

Exception in thread django-main-thread:
Traceback (most recent call last):
File "/usr/lib/python3.9/threading.py", line 954, in \_bootstrap_inner
self.run()
File "/usr/lib/python3.9/threading.py", line 892, in run
self.\_target(*self.\_args, \*\*self.\_kwargs)
File "/usr/local/lib/python3.9/dist-packages/django/utils/autoreload.py", line 54, in wrapper
fn(*args, **kwargs)
File "/usr/local/lib/python3.9/dist-packages/django/core/management/commands/runserver.py", line 109, in inner_run
autoreload.raise_last_exception()
File "/usr/local/lib/python3.9/dist-packages/django/utils/autoreload.py", line 77, in raise_last_exception
raise \_exception[1]
File "/usr/local/lib/python3.9/dist-packages/django/core/management/init.py", line 337, in execute
autoreload.check_errors(django.setup)()
File "/usr/local/lib/python3.9/dist-packages/django/utils/autoreload.py", line 54, in wrapper
fn(\*args, **kwargs)
File "/usr/local/lib/python3.9/dist-packages/django/init.py", line 24, in setup
apps.populate(settings.INSTALLED_APPS)
File "/usr/local/lib/python3.9/dist-packages/django/apps/registry.py", line 91, in populate
app_config = AppConfig.create(entry)
File "/usr/local/lib/python3.9/dist-packages/django/apps/config.py", line 90, in create
module = import_module(entry)
File "/usr/lib/python3.9/importlib/init.py", line 127, in import_module
return \_bootstrap.\_gcd_import(name[level:], package, level)
File "", line 1030, in \_gcd_import
File "", line 1007, in \_find_and_load
File "", line 984, in \_find_and_load_unlocked
ModuleNotFoundError: No module named 'corsheaders'
[-] Authentication failed at: 
[-] Can't login to get JWT

**Comment by Liquid1998** [comment]
pip3 install django-cors-headers


This should work.

**Comment by j3ssie** [comment]
The issue is no longer exist due to the repo having been upgraded to [Osmedeus Next Generation v4.0](https://twitter.com/OsmedeusEngine)
