### ISSUE TITLE
Can't login to get JWT; OS:Kali 2020.4

### ISSUE THREAD

**Issue by shariarr** [j3ssie/Osmedeus#195]
When I try to execute:
./osmedeus.py -example.com

It returns:
[*] Loading config file from: /root/.osmedeus/client.conf
----------------------------------------------------------------------
[RUN] Starting Django API
----------------------------------------------------------------------
Performing system checks...

System check identified no issues (0 silenced).
December 30, 2020 - 07:45:11
Django version 2.2.13, using settings 'rest.settings'
Starting development server at http://0.0.0.0:8000/
Quit the server with CONTROL-C.
Internal Server Error: /auth/api/token/
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.9/dist-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.9/dist-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.9/dist-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/rest_framework/views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python3.9/dist-packages/rest_framework/views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.9/dist-packages/rest_framework/views.py", line 476, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.9/dist-packages/rest_framework/views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/rest_framework_simplejwt/views.py", line 27, in post
    serializer.is_valid(raise_exception=True)
  File "/usr/local/lib/python3.9/dist-packages/rest_framework/serializers.py", line 235, in is_valid
    self._validated_data = self.run_validation(self.initial_data)
  File "/usr/local/lib/python3.9/dist-packages/rest_framework/serializers.py", line 433, in run_validation
    value = self.validate(value)
  File "/usr/local/lib/python3.9/dist-packages/rest_framework_simplejwt/serializers.py", line 75, in validate
    data['refresh'] = str(refresh)
  File "/usr/local/lib/python3.9/dist-packages/rest_framework_simplejwt/tokens.py", line 82, in __str__
    return token_backend.encode(self.payload)
  File "/usr/local/lib/python3.9/dist-packages/rest_framework_simplejwt/backends.py", line 35, in encode
    return token.decode('utf-8')
AttributeError: 'str' object has no attribute 'decode'
[30/Dec/2020 07:45:17] "POST /auth/api/token/ HTTP/1.1" 500 17226
[-] Authentication failed at: http://127.0.0.1:8000/auth/api/token/

        [!] This might happened by running Osmedeus with sudo but the install process running with normal user
        You should install the whole Osmedeus and running it with root user.
        Or whitelist masscan + nmap in sudoers file because it's required sudo permission.
        
[-] Can't login to get JWT

**Comment by Liquid1998** [comment]
I am getting the same error and also getting the error while installing...it says 404 not found...gorm.io/gorm/logger...gorm.io/gorm/callbacks.....gorm.io/gorm/migrator......gorm.io/gorm/migrator

Fix this issue please.....gorm.io is in now github.com as go-gorm

**Comment by Liquid1998** [comment]
@shariarr so, i have solved the issue....just install latest requrements.......open requrements.txt and remove all the version numbers and == signs....also add "slack" at the end of the list....and after that do "pip3 install -r requrements.txt"

**Comment by shariarr** [comment]
> @shariarr so, i have solved the issue....just install latest requrements.......open requrements.txt and remove all the version numbers and == signs....also add "slack" at the end of the list....and after that do "pip3 install -r requrements.txt"

What is python version???Mine is 3.9.I will give it a try and Thanks in advance.

**Comment by Liquid1998** [comment]
Mine is python3.9 as well and it is working fine now after installing
latest dependencies.have fun.

**Comment by shariarr** [comment]
> > @shariarr so, i have solved the issue....just install latest requrements.......open requrements.txt and remove all the version numbers and == signs....also add "slack" at the end of the list....and after that do "pip3 install -r requrements.txt"
> 
> What is python version???Mine is 3.9.I will give it a try and Thanks in advance.



> @shariarr so, i have solved the issue....just install latest requrements.......open requrements.txt and remove all the version numbers and == signs....also add "slack" at the end of the list....and after that do "pip3 install -r requrements.txt"

Worked perfectly....also worked on ubuntu vps with python 3.7.9

**Comment by shariarr** [comment]
Issue solved

**Comment by Liquid1998** [comment]
Glad to hear it!

**Comment by mhmh55516** [comment]
same error any solution ??
