### ISSUE TITLE
cant use osmedeus after install it

### ISSUE THREAD

**Issue by eyal-gabay** [j3ssie/Osmedeus#212]
i get this error after install

# python3 ./osmedeus.py -t c.com

Traceback (most recent call last):
  File "/home/eyal/opt/Osmedeus/./osmedeus.py", line 13, in <module>
    from lib.mode import routine
  File "/home/eyal/opt/Osmedeus/lib/mode/routine.py", line 6, in <module>
    from lib.mode import general
  File "/home/eyal/opt/Osmedeus/lib/mode/general.py", line 6, in <module>
    from modules import subdomain
ImportError: cannot import name 'subdomain' from 'modules' (/usr/lib/python3.9/site-packages/modules/__init__.py)

i cant understand why he isnt import the modules from the directory

do you know what i can do with it?

i use black arch linux

install like this:
cd /home/eyal/opt/
git clone https://github.com/j3ssie/Osmedeus
cd Osmedeus
./install.sh

**Comment by eyal-gabay** [comment]
found a way to fix it
sudo cp modules/* /usr/lib/python3.9/site-packages/modules/
