### ISSUE TITLE
panic: runtime error

### ISSUE THREAD

**Issue by hax0rgb** [j3ssie/osmedeus#225]
**Platform**: Ubuntu 20.04.2 64 bit
**Go Version**: go1.17.6 linux/amd64

Osmedeus installation: I used the premium bash script

On running the following command:
```
osmedeus health
```
I see the following output:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x7604a5]

goroutine 1 [running]:
os.(*File).Name(...)
	/usr/local/go/src/os/file.go:57
github.com/j3ssie/osmedeus/utils.InitLog(0x3748a80)
	/Users/j3ssie/go/src/github.com/j3ssie/osmedeus/utils/log.go:27 +0x85
github.com/j3ssie/osmedeus/cmd.initConfig()
	/Users/j3ssie/go/src/github.com/j3ssie/osmedeus/cmd/root.go:106 +0x45
github.com/spf13/cobra.(*Command).preRun(0xc0007ca780)
	/Users/j3ssie/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:886 +0x42
github.com/spf13/cobra.(*Command).execute(0xc0007ca780, {0x3779c38, 0x0, 0x0})
	/Users/j3ssie/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:822 +0x1db
github.com/spf13/cobra.(*Command).ExecuteC(0x37469a0)
	/Users/j3ssie/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:974 +0x3bc
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/j3ssie/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:902
github.com/j3ssie/osmedeus/cmd.Execute()
	/Users/j3ssie/go/src/github.com/j3ssie/osmedeus/cmd/root.go:30 +0x25
main.main()
	/Users/j3ssie/go/src/github.com/j3ssie/osmedeus/main.go:6 +0x17
```
I can verify other tools installed using go such as nuclei, subfinder etc. works fine. I only see the panic runtime error when I run the osmedeus scan.

**Comment by j3ssie** [comment]
You need to `sudo su` first before running this command since the setup is done on `root` user.

**Comment by hax0rgb** [comment]
I forgot that. All good now. Thanks :)
