### ISSUE TITLE
waiting for subdomain scanning

### ISSUE THREAD

**Issue by jepunband** [j3ssie/Osmedeus#38]
hi i get this "waiting for subdomain scanning module" ... it keeps going ..had to control C to stop it.

![Screenshot at 2019-06-08 21-48-51](https://user-images.githubusercontent.com/46950575/59148168-e1583700-8a37-11e9-9585-f36ed60702e5.png)

^CTraceback (most recent call last):
  File "./osmedeus.py", line 161, in <module>

    main()
  File "./osmedeus.py", line 157, in main
    parsing_argument(args)
  File "./osmedeus.py", line 77, in parsing_argument
    single_target(options)
  File "./osmedeus.py", line 97, in single_target
    routine.normal(options)
  File "/home/logan/github/Osmedeus/core/routine.py", line 32, in normal
    subdomain.SubdomainScanning(options)
  File "/home/logan/github/Osmedeus/modules/subdomain.py", line 23, in __init__
    self.initial()
  File "/home/logan/github/Osmedeus/modules/subdomain.py", line 36, in initial
    self.run()
  File "/home/logan/github/Osmedeus/modules/subdomain.py", line 51, in run
    utils.just_waiting(self.options, self.module_name, seconds=5)
  File "/home/logan/github/Osmedeus/core/utils.py", line 140, in just_waiting
    time.sleep(seconds)
KeyboardInterrupt
Fatal Python error: could not acquire lock for <_io.BufferedWriter name='<stdout>'> at interpreter shutdown, possibly due to daemon threads

Thread 0x00007f0c35101700 (most recent call first):
  File "/home/logan/github/Osmedeus/core/execute.py", line 28 in run
  File "/home/logan/github/Osmedeus/core/rest/cmd.py", line 83 in post
  File "/home/logan/github/Osmedeus/core/rest/decorators.py", line 18 in function_name
  File "/usr/local/lib/python3.7/dist-packages/flask_jwt_extended/view_decorators.py", line 103 in wrapper
  File "/usr/local/lib/python3.7/dist-packages/flask_restful/__init__.py", line 595 in dispatch_request
  File "/usr/lib/python3/dist-packages/flask/views.py", line 88 in view
  File "/usr/local/lib/python3.7/dist-packages/flask_restful/__init__.py", line 480 in wrapper
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1799 in dispatch_request
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1813 in full_dispatch_request
  File "/usr/lib/python3/dist-packages/flask/app.py", line 2292 in wsgi_app
  File "/usr/lib/python3/dist-packages/flask/app.py", line 2309 in __call__
  File "/usr/lib/python3/dist-packages/werkzeug/serving.py", line 258 in execute
  File "/usr/lib/python3/dist-packages/werkzeug/serving.py", line 270 in run_wsgi
  File "/usr/lib/python3/dist-packages/werkzeug/serving.py", line 328 in handle_one_request
  File "/usr/lib/python3.7/http/server.py", line 426 in handle
  File "/usr/lib/python3/dist-packages/werkzeug/serving.py", line 293 in handle
  File "/usr/lib/python3.7/socketserver.py", line 720 in __init__
  File "/usr/lib/python3.7/socketserver.py", line 360 in finish_request
  File "/usr/lib/python3.7/socketserver.py", line 650 in process_request_thread
  File "/usr/lib/python3.7/threading.py", line 865 in run
  File "/usr/lib/python3.7/threading.py", line 917 in _bootstrap_inner
  File "/usr/lib/python3.7/threading.py", line 885 in _bootstrap

Current thread 0x00007f0c3813c740 (most recent call first):
Aborted

**Comment by j3ssie** [comment]
It's completely fine cause brute force subdomain take really long time if your network slow.
Maybe I'll add some options for slow network later.

**Comment by ximiluliyi** [comment]
127.0.0.1:5000的登录密码是多少？

**Comment by ximiluliyi** [comment]
What is the login password for 127.0.0.1:5000?

**Comment by 1522402210** [comment]
@j3ssie  me too

**Comment by 1522402210** [comment]
@j3ssie 
other qa:

python3 ./osmedeus.py -t c.com
.
Everything is normal here
...
Then, I started to report an error here：
[+] Writing /Users/x/OSmedeus_Auto_Recon/core/rest/storages/activities.json
Traceback (most recent call last):
  File "./osmedeus.py", line 161, in <module>
    main()
  File "./osmedeus.py", line 157, in main
    parsing_argument(args)
  File "./osmedeus.py", line 77, in parsing_argument
    single_target(options)
  File "./osmedeus.py", line 97, in single_target
    routine.normal(options)
  File "/Users/x/OSmedeus_Auto_Recon/core/routine.py", line 44, in normal
    recon.Recon(options)
  File "/Users/x/OSmedeus_Auto_Recon/modules/recon.py", line 28, in __init__
    self.initial()
  File "/Users/x/OSmedeus_Auto_Recon/modules/recon.py", line 40, in initial
    self.resolve_ip()
  File "/Users/x/OSmedeus_Auto_Recon/modules/recon.py", line 148, in resolve_ip
    with open(output_path, 'r') as i:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/x/OSmedeus_Auto_Recon/workspaces/c.com/subdomain/massdns-IP-c.com.txt'

**Comment by j3ssie** [comment]
@1522402210 Look like you're not running **massdns** successfully. 
But I remember doesn't include that in the normal routine which is your command `python3 ./osmedeus.py -t c.com` run on that.

**Comment by j3ssie** [comment]
Due to Osmedeus upgraded into v2.0, this issue is no longer exist.
Please use the new version and send me a feedback.
Thank you.
