### ISSUE TITLE
ScreenShot the target: save to path

### ISSUE THREAD

**Issue by dizcza** [j3ssie/Osmedeus#55]
When I test some domain (`-t` option), I got the error and then osmedeus hangs.
```
--~~~=[  ScreenShot the target ]=~~~--
Traceback (most recent call last):
  File "./osmedeus.py", line 151, in <module>
    main()
  File "./osmedeus.py", line 147, in main
    parsing_argument(args)
  File "./osmedeus.py", line 53, in parsing_argument
    single_target(options)
  File "./osmedeus.py", line 84, in single_target
    routine.normal(options)
  File "/home/dizcza/tools/Osmedeus/core/routine.py", line 43, in normal
    screenshot.ScreenShot(options)
  File "/home/dizcza/tools/Osmedeus/modules/screenshot.py", line 25, in __init__
    self.initial()
  File "/home/dizcza/tools/Osmedeus/modules/screenshot.py", line 46, in initial
    self.screenshots(self.is_direct)
  File "/home/dizcza/tools/Osmedeus/modules/screenshot.py", line 69, in screenshots
    if not utils.not_empty_file(input_file):
  File "/home/dizcza/tools/Osmedeus/core/utils.py", line 158, in not_empty_file
    fpath = os.path.normpath(filepath)
  File "/usr/lib/python3.7/posixpath.py", line 340, in normpath
    path = os.fspath(path)
TypeError: expected str, bytes or os.PathLike object, not bool
```

### Environment
python3.7
Kali, latest updates
osmedeus: git master branch

----
Issues I ran into with `-t example.com`:
1. 
```
--==[ Check the output: /home/dizcza/tools/Osmedeus/workspaces/example.com/cors/example.com-corstest.txt
[+] Writing /home/dizcza/tools/Osmedeus/workspaces/example.com/cors/std-example.com-corstest.std
[+] Writing /home/dizcza/tools/Osmedeus/core/rest/storages/example.com/activities.json
Traceback (most recent call last):
  File "/home/dizcza/tools/Osmedeus/plugins/CORScanner/cors_scan.py", line 8, in <module>
    from common.corscheck import CORSCheck
  File "/home/dizcza/tools/Osmedeus/plugins/CORScanner/common/corscheck.py", line 1, in <module>
    import requests, json, os, inspect, tldextract
ImportError: No module named tldextract
```

2.
```
--~~~=:>[ Starting scraping IP from Censys ]>
Traceback (most recent call last):
  File "/home/dizcza/tools/Osmedeus/plugins/IPOsint/ip-osint.py", line 146, in <module>
    main()
  File "/home/dizcza/tools/Osmedeus/plugins/IPOsint/ip-osint.py", line 142, in main
    parsing_argument(args)
  File "/home/dizcza/tools/Osmedeus/plugins/IPOsint/ip-osint.py", line 91, in parsing_argument
    single_target()
  File "/home/dizcza/tools/Osmedeus/plugins/IPOsint/ip-osint.py", line 101, in single_target
    cencys.Censys(options)
  File "/home/dizcza/tools/Osmedeus/plugins/IPOsint/modules/cencys.py", line 16, in __init__
    self.initial()
  File "/home/dizcza/tools/Osmedeus/plugins/IPOsint/modules/cencys.py", line 19, in initial
    real_data = self.get_real_content()
  File "/home/dizcza/tools/Osmedeus/plugins/IPOsint/modules/cencys.py", line 51, in get_real_content
    response = core.open_with_chrome(url)
  File "/home/dizcza/tools/Osmedeus/plugins/IPOsint/modules/core.py", line 166, in open_with_chrome
    browser = webdriver.Chrome(executable_path=chromedriver, options=options)
  File "/home/dizcza/.local/lib/python3.7/site-packages/selenium/webdriver/chrome/webdriver.py", line 81, in __init__
    desired_capabilities=desired_capabilities)
  File "/home/dizcza/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/home/dizcza/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/home/dizcza/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/dizcza/.local/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: Chrome version must be between 70 and 73
  (Driver info: chromedriver=73.0.3683.68 (47787ec04b6e38e22703e856e101e840b65afe72),platform=Linux 4.19.0-kali4-amd64 x86_64)
```

**Comment by j3ssie** [comment]
Duplicate Issue here https://github.com/j3ssie/Osmedeus/issues/48
