### ISSUE TITLE
Getting Error While Running

### ISSUE THREAD

**Issue by d1pakda5** [j3ssie/Osmedeus#60]
Here is the error 
./osmedeus.py -t example.com
Traceback (most recent call last):
  File "./osmedeus.py", line 182, in <module>
    main()
  File "./osmedeus.py", line 97, in main
    config.banner(__version__, __author__)
  File "/root/Osmedeus/core/config.py", line 54, in banner
    """.format(C, G, P, R, B, GR, __version__, __author__))
UnicodeEncodeError: 'ascii' codec can't encode character '\xaf' in position 1005: ordinal not in range(128)

**Comment by j3ssie** [comment]
It's really weird. Did you run it with **python3**? And btw what's your OS?

**Comment by d1pakda5** [comment]
yes running with python3 and os is Debian GNU/Linux 9 (stretch)

**Comment by j3ssie** [comment]
Can you run `./osmedeus.py -hh` to make sure the error is in the print banner function

**Comment by d1pakda5** [comment]
Hi
i got the following error 
Traceback (most recent call last):
  File "./osmedeus.py", line 182, in <module>
    main()
  File "./osmedeus.py", line 97, in main
    config.banner(__version__, __author__)
  File "/root/Osmedeus/core/config.py", line 54, in banner
    """.format(C, G, P, R, B, GR, __version__, __author__))
UnicodeEncodeError: 'ascii' codec can't encode character '\xaf' in position 1005: ordinal not in range(128)

**Comment by j3ssie** [comment]
I still have no idea why this happened. 
The only way I can think of is you comment this line https://github.com/j3ssie/Osmedeus/blob/master/osmedeus.py#L97 from `osmedeus.py` file.

**Comment by d1pakda5** [comment]
commenting out that line fixed the issue but still throwing some error 
Traceback (most recent call last):
  File "core/app.py", line 128, in <module>
    app.run(host=host, port=port, debug=debug, ssl_context=(cert_path, key_path))
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 943, in run
    run_simple(host, port, self, **options)
  File "/usr/local/lib/python3.5/dist-packages/werkzeug/serving.py", line 1009, in run_simple
    inner()
  File "/usr/local/lib/python3.5/dist-packages/werkzeug/serving.py", line 962, in inner
    fd=fd,
  File "/usr/local/lib/python3.5/dist-packages/werkzeug/serving.py", line 805, in make_server
    host, port, app, request_handler, passthrough_errors, ssl_context, fd=fd
  File "/usr/local/lib/python3.5/dist-packages/werkzeug/serving.py", line 723, in __init__
    self.socket = ssl_context.wrap_socket(sock, server_side=True)
  File "/usr/local/lib/python3.5/dist-packages/werkzeug/serving.py", line 611, in wrap_socket
    **kwargs
  File "/usr/lib/python3.5/ssl.py", line 1069, in wrap_socket
    ciphers=ciphers)
  File "/usr/lib/python3.5/ssl.py", line 691, in __init__
    self._context.load_cert_chain(certfile, keyfile)

**Comment by j3ssie** [comment]
well I got it, you need at least `python 3.6` so maybe update your python will resolve this.

**Comment by elabshyderabad** [comment]
Hi 

I am also facing the same issue and my python version 3.6.9

Pls Help

**Comment by elabshyderabad** [comment]
> commenting out that line fixed the issue but still throwing some error
> Traceback (most recent call last):
> File "core/app.py", line 128, in
> app.run(host=host, port=port, debug=debug, ssl_context=(cert_path, key_path))
> File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 943, in run
> run_simple(host, port, self, **options)
> File "/usr/local/lib/python3.5/dist-packages/werkzeug/serving.py", line 1009, in run_simple
> inner()
> File "/usr/local/lib/python3.5/dist-packages/werkzeug/serving.py", line 962, in inner
> fd=fd,
> File "/usr/local/lib/python3.5/dist-packages/werkzeug/serving.py", line 805, in make_server
> host, port, app, request_handler, passthrough_errors, ssl_context, fd=fd
> File "/usr/local/lib/python3.5/dist-packages/werkzeug/serving.py", line 723, in **init**
> self.socket = ssl_context.wrap_socket(sock, server_side=True)
> File "/usr/local/lib/python3.5/dist-packages/werkzeug/serving.py", line 611, in wrap_socket
> **kwargs
> File "/usr/lib/python3.5/ssl.py", line 1069, in wrap_socket
> ciphers=ciphers)
> File "/usr/lib/python3.5/ssl.py", line 691, in **init**
> self._context.load_cert_chain(certfile, keyfile)

Hi,

I am also facing the same issue and my python version is also 3.6.9 

Pls help
