### ISSUE TITLE
UnboundLocalError: local variable 'domain' referenced before assignment

### ISSUE THREAD

**Issue by cybert79** [j3ssie/Osmedeus#78]
Hi,

When running python3 osmedeus -t sub.domain.com -w workspace I get the following error;

Any idea on how to fix it?

[*] Starting pre routine for SubdomainScanning
[*] Waiting for SubdomainScanning module
[*] Starting post routine for SubdomainScanning
[*] Starting pre routine for SubdomainScanning
[+] Starting Amass
[+] Starting Subfinder
[+] Starting assetfinder
[+] Starting findomain
[+] Starting gobuster
[*] Waiting for SubdomainScanning module
[*] Waiting for SubdomainScanning module
[*] Waiting for SubdomainScanning module
[*] Waiting for SubdomainScanning module
[*] Waiting for SubdomainScanning module
[*] Starting post routine for SubdomainScanning
[+] Cleaning for findomain:clean_findomain
Traceback (most recent call last):
  File "osmedeus.py", line 148, in <module>
    main()
  File "osmedeus.py", line 144, in main
    parsing_argument(args)
  File "osmedeus.py", line 47, in parsing_argument
    single_target(options)
  File "osmedeus.py", line 59, in single_target
    routine.routine_handle(options)
  File "/opt/Osmedeus/lib/mode/routine.py", line 20, in routine_handle
    general.handle(options)
  File "/opt/Osmedeus/lib/mode/general.py", line 30, in handle
    single_handle(options)
  File "/opt/Osmedeus/lib/mode/general.py", line 34, in single_handle
    subdomain.SubdomainScanning(options)
  File "/opt/Osmedeus/modules/skeleton.py", line 16, in __init__
    self.initial()
  File "/opt/Osmedeus/modules/skeleton.py", line 33, in initial
    self.routine()
  File "/opt/Osmedeus/modules/skeleton.py", line 70, in routine
    self.really_routine(self.mid_commands)
  File "/opt/Osmedeus/modules/skeleton.py", line 76, in really_routine
    self.sub_routine(commands, kind='post')
  File "/opt/Osmedeus/modules/skeleton.py", line 91, in sub_routine
    eval(eval_string)
  File "<string>", line 1, in <module>
  File "/opt/Osmedeus/modules/subdomain.py", line 82, in clean_findomain
    'cleaned_output'), "\n".join(domain))
UnboundLocalError: local variable 'domain' referenced before assignment

**Comment by cybert79** [comment]
Ok, it works! thanks!
