### ISSUE TITLE
Enable Slack notification problem

### ISSUE THREAD

**Issue by Tarekzidan19** [j3ssie/osmedeus#79]
I have installed the tool using docker and it worked great

i have edited the slack settings ~/.osmedeus/config.conf 

[Slack]
local_name = JJ
bot_token = xoxp-xxx...
log_channel = None
log_name = logcmd
status_channel = None
status_name = osme1
stds_channel = None
stds_name = stds
report_channel = None
report_name = report
verbose_report_channel = None
verbose_report_name = verbose-report

then i restart the container using : docker restart osmedeus

i run the tool with --slack option
but i didn't receive an notification ?

**Comment by saddean** [comment]
How i can disable slack noti bro

**Comment by Tarekzidan19** [comment]
@saddean 
it's disabled by default
Slack notification will be enabled only if you pass the argument " --slack "

**Comment by saddean** [comment]
@Tarekzidan19 
i run command ``./osmedeus.py -t domain.com`` , however , ``slack noti sending`` is enable

```
[*] Sending done notification to slack
[-] Fail to send noti to slack
[*] Sending report notification to slack
Traceback (most recent call last):
  File "./osmedeus.py", line 159, in <module>
    main()
  File "./osmedeus.py", line 155, in main
    parsing_argument(args)
  File "./osmedeus.py", line 58, in parsing_argument
    single_target(options)
  File "./osmedeus.py", line 66, in single_target
    routine.routine_handle(options)
  File "/home/ttuongann/tool/Osmedeus/lib/mode/routine.py", line 28, in routine_handle
    general.handle(options)
  File "/home/ttuongann/tool/Osmedeus/lib/mode/general.py", line 31, in handle
    single_handle(options)
  File "/home/ttuongann/tool/Osmedeus/lib/mode/general.py", line 42, in single_handle
    stoscan.StoScan(options)
  File "/home/ttuongann/tool/Osmedeus/modules/skeleton.py", line 17, in __init__
    self.initial()
  File "/home/ttuongann/tool/Osmedeus/modules/skeleton.py", line 39, in initial
    self.additional_routine()
  File "/home/ttuongann/tool/Osmedeus/modules/skeleton.py", line 120, in additional_routine
    'report', self.options, output=slack_report)
  File "/home/ttuongann/tool/Osmedeus/lib/noti/slack_noti.py", line 53, in slack_notification
    slack_file(options, output)
  File "/home/ttuongann/tool/Osmedeus/lib/noti/slack_noti.py", line 139, in slack_file
    filetype='text'
  File "/usr/local/lib/python3.6/dist-packages/slack/web/client.py", line 715, in files_upload
    return self.api_call("files.upload", files={"file": file}, data=kwargs)
  File "/usr/local/lib/python3.6/dist-packages/slack/web/base_client.py", line 154, in api_call
    return self._event_loop.run_until_complete(future)
  File "/usr/lib/python3.6/asyncio/base_events.py", line 484, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.6/dist-packages/slack/web/base_client.py", line 223, in _send
    return SlackResponse(**{**data, **res}).validate()
  File "/usr/local/lib/python3.6/dist-packages/slack/web/slack_response.py", line 174, in validate
    raise e.SlackApiError(message=msg, response=self.data)
slack.errors.SlackApiError: The request to the Slack API failed.
The server responded with: {'ok': False, 'error': 'invalid_auth'}
^CError in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/popen_fork.py", line 28, in poll
    pid, sts = os.waitpid(self.pid, flag)
```

**Comment by saddean** [comment]
@Tarekzidan19 
i run command ``./osmedeus.py -t domain.com`` , however , ``slack noti sending`` is enable

```
[*] Sending done notification to slack
[-] Fail to send noti to slack
[*] Sending report notification to slack
Traceback (most recent call last):
  File "./osmedeus.py", line 159, in <module>
    main()
  File "./osmedeus.py", line 155, in main
    parsing_argument(args)
  File "./osmedeus.py", line 58, in parsing_argument
    single_target(options)
  File "./osmedeus.py", line 66, in single_target
    routine.routine_handle(options)
  File "/home/vps/tool/Osmedeus/lib/mode/routine.py", line 28, in routine_handle
    general.handle(options)
  File "/home/vps/tool/Osmedeus/lib/mode/general.py", line 31, in handle
    single_handle(options)
  File "/home/vps/tool/Osmedeus/lib/mode/general.py", line 42, in single_handle
    stoscan.StoScan(options)
  File "/home/vps/tool/Osmedeus/modules/skeleton.py", line 17, in __init__
    self.initial()
  File "/home/vps/tool/Osmedeus/modules/skeleton.py", line 39, in initial
    self.additional_routine()
  File "/home/vps/tool/Osmedeus/modules/skeleton.py", line 120, in additional_routine
    'report', self.options, output=slack_report)
  File "/home/vps/tool/Osmedeus/lib/noti/slack_noti.py", line 53, in slack_notification
    slack_file(options, output)
  File "/home/vps/tool/Osmedeus/lib/noti/slack_noti.py", line 139, in slack_file
    filetype='text'
  File "/usr/local/lib/python3.6/dist-packages/slack/web/client.py", line 715, in files_upload
    return self.api_call("files.upload", files={"file": file}, data=kwargs)
  File "/usr/local/lib/python3.6/dist-packages/slack/web/base_client.py", line 154, in api_call
    return self._event_loop.run_until_complete(future)
  File "/usr/lib/python3.6/asyncio/base_events.py", line 484, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.6/dist-packages/slack/web/base_client.py", line 223, in _send
    return SlackResponse(**{**data, **res}).validate()
  File "/usr/local/lib/python3.6/dist-packages/slack/web/slack_response.py", line 174, in validate
    raise e.SlackApiError(message=msg, response=self.data)
slack.errors.SlackApiError: The request to the Slack API failed.
The server responded with: {'ok': False, 'error': 'invalid_auth'}
^CError in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/popen_fork.py", line 28, in poll
    pid, sts = os.waitpid(self.pid, flag)
```

**Comment by dzhenway** [comment]
Hi @j3ssie 

I got problem when tried send notif to slack

```
[+] Clean old activities for razer.com:SubdomainScanning
[*] Sending status notification to slack
[-] Fail to send noti to slack
```

This is my Config :

```
# Osmedeus
export LOG_CHANNEL=CGXXXXXX
export STATUS_CHANNEL=CGXXXXXX                                                                                          export REPORT_CHANNEL=CGosmedeus
export STDS_CHANNEL=CGXXXXXXX                                                                                           export SLACK_BOT_TOKEN=xoxb-xxxx
export GITHUB_API_KEY=xxxxx
```

And i just followed your setup, after setup my `.bashrc` 
then `source ~/.bashrc` to load that.

Finally, run `python3 scripts/reload.py` to load those configs to your API server.

```
wayc0de@DESKTOP-9C0TVKV:~/tools/Osmedeus$ python3 scripts/reload.py
----------------------------------------------------------------------
[RUN] Reload routine and config for server
----------------------------------------------------------------------
```

I can verify it by checking content of `~/.osmedeus/server.conf` file.

```
[Enviroments]
workspaces = /home/wayc0de/.osmedeus/workspaces
plugins_path = /home/wayc0de/tools/Osmedeus/plugins
go_path = /home/wayc0de/tools/Osmedeus/plugins/go
data_path = /home/wayc0de/tools/Osmedeus/data
alias_path = /home/wayc0de/tools/Osmedeus/lib/alias
github_api_key = xxxxxxx
healthcheck = None

[Slack]
local_name = JJ
slack_bot_token = xoxb-xxxxxxxx
log_channel = CGXXXXXX
log_name = logcmd
status_channel = CGXXXXXX
status_name = status
stds_channel = CGXXXXXXX
stds_name = stds
report_channel = CGosmedeus
report_name = report
verbose_report_channel = None
verbose_report_name = verbose-report

[Monitor]
backups = /home/wayc0de/.osmedeus/backups
monitors = /home/wayc0de/.osmedeus/monitors
monitor_level = final
slack_monitor_token = None
new_channel = None
new_name = None
missing_channel = None
missing_name = None
```

Maybe i wrong setup on `report_channel` name? 

Thank before :)

**Comment by dwisiswant0** [comment]
same here. i've followed all steps here (https://j3ssie.github.io/Osmedeus/installation/token-setup/#setup-slack-notification-in-osmedeus). and my `~/.osmedeus/server.conf` it still doesn't change anything when i `cat` dat file.

**Comment by Hax0rG1rl** [comment]
Hi, 

I have the same issue trying to enable slack notifications. 

"same here. i've followed all steps here (https://j3ssie.github.io/Osmedeus/installation/token-setup/#setup-slack-notification-in-osmedeus). and my ~/.osmedeus/server.conf it still doesn't change anything when i cat dat file." does apply completely to me as well. 

OS: Ubuntu 18.04.3. 

Any advice regards how can we fix / debug this? 

Thanks!

**Comment by smartis63** [comment]
root@PC192:/home/smartis/Scrivania/Osmedeus# ./osmedeus.py -t yahoo.com
Traceback (most recent call last):
  File "./osmedeus.py", line 10, in <module>
    from lib.client import config
  File "/home/smartis/Scrivania/Osmedeus/lib/client/config.py", line 7, in <module>
    from lib.core import execute
  File "/home/smartis/Scrivania/Osmedeus/lib/core/execute.py", line 8, in <module>
    from core import utils
ImportError: cannot import name 'utils' from 'core' (/usr/local/lib/python3.8/dist-packages/ufonet-1.6-py3.8.egg/core/__init__.py)

**Comment by j3ssie** [comment]
The issue is no longer exist due to the repo having been upgraded to [Osmedeus Next Generation v4.0](https://twitter.com/OsmedeusEngine)
