### ISSUE TITLE
Metabigor config file error

### ISSUE THREAD

**Issue by sieunhando** [j3ssie/Osmedeus#81]
I think the right path is `/root/Osmedeus/plugins/Metabigor/sample-config.conf`
This is full logs
```
[*] New config file created: /root/.metabigor/config.conf
Traceback (most recent call last):
  File "/root/Osmedeus/plugins/Metabigor/metabigor.py", line 95, in <module>
    main()
  File "/root/Osmedeus/plugins/Metabigor/metabigor.py", line 91, in main
    parsing_argument(args)
  File "/root/Osmedeus/plugins/Metabigor/metabigor.py", line 16, in parsing_argument
    options = config.config(args)
  File "/root/Osmedeus/plugins/Metabigor/core/config.py", line 157, in config
    shutil.copyfile(cwd + '/sample-config.conf', config_path)
  File "/usr/lib/python3.7/shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: '/root/Osmedeus/sample-config.conf'
```

**Comment by j3ssie** [comment]
Thanks for raise the issue. Will fix my **Metabigor** soon.
I'm not getting this because I'm just copying my Metabigor config on a test machine.

**Comment by j3ssie** [comment]
This should be fixed now.
